networks:
  okay_network:
    driver: bridge

services:
  postgres:
    networks:
      - okay_network
    image: postgres:latest
    container_name: okay-api-db
    environment:
      POSTGRES_NAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME} -h localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    networks:
      - okay_network
    image: node:20.18-slim
    container_name: okay_api
    working_dir: /usr/src/app
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /app/node_modules
    command: ['yarn', 'start:dev']
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
