networks:
  okay_network:
    driver: bridge

services:
  postgres:
    networks:
      - okay_network
    image: postgres:latest
    container_name: okay-api-db
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: okay-api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nest_user -d nest_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    networks:
      - okay_network
    image: node:20.18-slim
    container_name: okay_api
    working_dir: /usr/src/app
    environment:
      DB_HOST: mysql
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: ["npm", "run", "start:dev"]
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: