networks:
  okay_network:
    driver: bridge

services:
  postgres:
    networks:
      - okay_network
    image: postgres:latest
    container_name: okay-api-db
    environment:
      POSTGRES_NAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME} -h localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    networks:
      - okay_network
    image: node:20.18-slim
    container_name: okay_api
    working_dir: /usr/src/app
    environment:
      # Application settings
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}

      # Database settings
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGGING: ${DB_LOGGING}

      # Security settings
      COOKIE_SECRET: ${COOKIE_SECRET}
      SECURE_COOKIES: ${SECURE_COOKIES}
      THROTTLE_TTL: ${THROTTLE_TTL}
      THROTTLE_LIMIT: ${THROTTLE_LIMIT}

      # Auth0 configuration
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /app/node_modules
      # - /usr/src/app/node_modules
    command: ['npm', 'run', 'start:dev']
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
